# Generated by Django 5.0.6 on 2024-06-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=800)),
                ('last_name', models.CharField(max_length=800)),
                ('country', models.CharField(choices=[('uz', 'Uzbekistan'), ('rus', 'Rossiya'), ('usa', 'America')], default='uz', max_length=70)),
                ('subject', models.TextField()),
            ],
        ),
    ]
